---
title: "Registration Information"
format: html
---

----------------------------------------------------------------------

## Symposium Registration

Researchers from all institutions are welcome to register; however, please note that in-person attendance is required. Complimentary lunch will be provided for reservations made by March 12. The registration link is attached in the bottom of home page, you can also register here: [**Click here to register for Symposium 2025!**](https://docs.google.com/forms/d/e/1FAIpQLSeFLIrPz0kwp0TFKJLpNdbs3dYRzF0t8hcry2C_JRePVRLMSw/viewform?usp=header).

---------------------------------------------------------------------

## Poster Registration

We wholeheartedly encourage every researchers to participate and showcase their innovative work, and we welcome institutions across the region to join in. Don’t miss out on this exciting opportunity to present your research and gain valuable recognition! If you want to participate poster session, [please click here](https://docs.google.com/forms/d/e/1FAIpQLSetdMwOBPiGi2psZv-bDyl0oIrOypKEIot5OxC7KKEKs2PI8g/viewform?usp=header) and register by March 12. All researchers, including faculty, professionals, students and trainees, are encouraged to submit and present a poster at the symposium. But to ensure a fair comparison, only students and postdoctoral researchers will be considered for the poster award competition this year.

------------------------------------------------------------------------


Please register the symposium before [**March 12th**]{style="color:blue;"}! If you are interested in poster session, please submit the poster session registration before [**March 12th**]{style="color:blue;"}!
